require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails/DynamicFindBy:
  Enabled: false

I18n/GetText/DecorateString:
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateStringFormattingUsingInterpolation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/seeds/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Naming/VariableNumber:
  Exclude:
    - config/initializers/*.rb
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/Output:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
      - feature
      - scenario

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
