require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-rspec

AllCops:
  NewCops: enable

I18n/GetText/DecorateString:
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/Output:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
      - feature
      - scenario

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
