default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: teacherss_development

test:
  <<: *default
  database: teacherss_test

production:
  <<: *default
  database: teacherss_production
  username: teacherss
  password: <%= ENV["TEACHERSS_DATABASE_PASSWORD"] %>
