---
name: Docker CI
on:
  workflow_run:
    workflows: ["main"]
    branches: [make-docker-action-not-required]
    types: 
      - completed
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  docker_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
      - name: Run a test
        run: bin/docker-test
...
