---
name: Docker CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check job without docker
        run: exit 0
        if: ${{jobs.test.conslusion == 'success' &&  jobs.quality.conslusion == 'success'}}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check job without docker
        run: exit 0
        if: ${{jobs.test.conslusion == 'success' &&  jobs.quality.conslusion == 'success'}}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a test
        run: bin/docker-test
...
