---
name: Docker CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  docker_quality:
    needs: test, quality
    runs-on: ubuntu-latest
    steps:
      - name: Check another jobs
        if: ${{(needs.test.result == 'success' &&  needs.quality.result == 'success')}}
        run: exit 0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
  docker_test:
    needs: test, quality
    runs-on: ubuntu-latest
    steps:
      - name: Check another jobs
        if: ${{(needs.test.result == 'success' &&  needs.quality.result == 'success')}}
        run: exit 0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a test
        run: bin/docker-test
...
