---
name: Docker CI
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  quality_if_workflow_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
      - name: Run a test
        run: bin/docker-test
  quality_if_workflow_success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Success!'
...
