---
name: Docker CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  docker_quality:
    # if: ${{ github.event_name == 'push'  && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
      - name: Run a test
        run: bin/docker-test
...
