---
name: Docker CI
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  quality_if_workflow_failure:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'Success!'
      - name: Checkout code
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Run a quality
        run: bin/docker-quality
      - name: Run a test
        run: bin/docker-test
...
