---
name: Docker CI
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches: [ 2-make-docker-jobs-success-if-jobs-without-docker-success, master ]
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  docker_quality:
    runs-on: ubuntu-latest
    needs: test, quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Run a quality
        run: bin/docker-quality
  docker_test:
    runs-on: ubuntu-latest
    needs: test, quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Run a test
        run: bin/docker-test
...
