---
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  RAILS_ENV: test
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a quality
        run: bin/docker-quality
      - name: Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a test
        run: bin/docker-test
...
